name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  host-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run host unit tests
        run: ./run_tests.sh
